{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medical-imaging-platform.fullname" . }}-api
  labels:
    {{- include "medical-imaging-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
{{- end }}
{{- if .Values.reviewerUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medical-imaging-platform.fullname" . }}-reviewer-ui
  labels:
    {{- include "medical-imaging-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: reviewer-ui
spec:
  type: {{ .Values.reviewerUi.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: reviewer-ui
  ports:
    - name: http
      port: {{ .Values.reviewerUi.service.port }}
      targetPort: http
{{- end }}
